name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install Depedecies
      run: |
        pwd
        echo ${GITHUB_WORKSPACE}
        current_path=$(pwd)
        sudo apt-get update -y 
        sudo apt-get install -qq -y --no-install-recommends wget git-core patchelf unzip zip gzip tar xz-utils 
    - name: Download FFmpeg
      run: |
        echo "Download ffmpeg-n4.4-linux"
        wget https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n4.4-latest-linux64-gpl-shared-4.4.tar.xz -q -O ffmpeg-n4.4-linux64.tar.xz
        tar xf ffmpeg-n4.4-linux64.tar.xz && rm ffmpeg-n4.4-linux64.tar.xz && mv ffmpeg* linux64
        echo "Download ffmpeg-n4.4-windows"
        wget https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n4.4-latest-win64-gpl-shared-4.4.zip -q -O ffmpeg-n4.4-win64.zip
        unzip -q ffmpeg-n4.4-win64.zip && rm ffmpeg-n4.4-win64.zip && mv ffmpeg* win64    
        # Delete extra files
        rm linux64/bin/ffmpeg
        rm linux64/bin/ffplay
        rm linux64/bin/ffprobe
        rm win64/bin/*.exe
        rm linux64/LICENSE*
        rm win64/LICENSE*
        rm linux64/doc -R
        rm win64/doc -R
    - name: Patch FFmpeg
      run: |
        echo "Patch ffmpeg-n4.4-linux"     
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libpostproc.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libavdevice.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libavcodec.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libswscale.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libswresample.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libavformat.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libavutil.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libavfilter.so
    - name: Pack FFmpeg
      run: |
        echo "Packing FFmpeg"
        dotnet pack nuget/FFMpeg.runtime.csproj -c Release -o ./publish
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: publish/*       
        

