name: .NET

on:
  push:
    branches: [ "master", "v4.4.4", "v5.1.4", "v6.1.1" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install Depedecies
      run: |
        pwd
        echo ${GITHUB_WORKSPACE}
        current_path=$(pwd)
        sudo apt-get update -y 
        sudo apt-get install -qq -y --no-install-recommends wget curl git-core patchelf unzip zip gzip tar xz-utils 
    - name: Download FFmpeg
      run: |
        echo "Download ffmpeg-n5.1.4-linux"
        curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-11-30-12-55/ffmpeg-n5.1.4-linux64-gpl-shared-5.1.tar.xz -o ffmpeg-n5.1.4-linux64.tar.xz
        tar xf ./ffmpeg-n5.1.4-linux64.tar.xz && rm ffmpeg-n5.1.4-linux64.tar.xz && mv ffmpeg-n5* linux64
        echo "Download ffmpeg-n4.4-windows"
        curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-11-30-12-55/ffmpeg-n5.1.4-win64-gpl-shared-5.1.zip -o ffmpeg-n5.1.4-win64.zip
        unzip ./ffmpeg-n5.1.4-win64.zip && rm ffmpeg-n5.1.4-win64.zip && mv ffmpeg-n5* win64
        # Delete extra files
        rm linux64/bin/*
        rm win64/bin/*.exe
        rm linux64/LICENSE*
        rm win64/LICENSE*
        rm linux64/doc -R
        rm win64/doc -R
    - name: Patch FFmpeg
      run: |
        echo "Patch ffmpeg-n5.1.4-linux"     
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libpostproc.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libavdevice.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libavcodec.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libswscale.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libswresample.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libavformat.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libavutil.so
        patchelf --set-rpath '$ORIGIN/.' linux64/lib/libavfilter.so
    - name: Pack FFmpeg
      run: |
        echo "Packing FFmpeg"
        dotnet pack FFMpeg.runtime.csproj -c Release -o ./publish
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: publish/*       
        

